### ISSUE TITLE
Compatibility with G Suite

### ISSUE THREAD

**Issue by sombatos** [zbateson/mail-mime-parser#100]
Starting February 15, 2021, G Suite accounts will only allow access to apps using OAuth
https://github.com/google/gmail-oauth2-tools/issues/18

**Comment by zbateson** [comment]
@sombatos -- mail-mime-parser only parses raw email (RFC 822 and its successors), it doesn't provide an IMAP/POP/mail retrieval api.  Please reopen if I misunderstood something.
