### ISSUE TITLE
Attachment Problems

### ISSUE THREAD

**Issue by spectrumvoip** [zbateson/mail-mime-parser#103]
[good_bad_eml_sample.txt](https://github.com/zbateson/mail-mime-parser/files/4013205/good_bad_eml_sample.txt)
Hi,

We are having problems with a couple of senders and their pdf attachments.  We are receiving emails and processing them with php scripts but our process isn't reading the pdf correctly for just a couple of non-related users. It seems to be only senders who use GoDaddy as their email provider.

I think I've narrowed it down to the attachment section is missing a carriage return/line feed before the separator.

See attached where the good.eml file has an extra carriage return but the bad.eml doesn't.

Is there something I can do to fix this or do I need to try to get GoDaddy to do something?

Thanks,
Shanon

**Comment by zbateson** [comment]
Hi @spectrumvoip,

The extra line *shouldn't* be an issue, that's definitely valid to have it either way (with or without that extra line).  Just to rule out a corrupt email though, have you tried opening the "bad" email in question in an email client like Thunderbird and tried to open the attachment to confirm it's not corrupt?

**Comment by spectrumvoip** [comment]
Thanks, that helped.  And the emails open with an email client and the pdf files open fine.

I think I've narrowed to the fact that the broken files are coming with a charset identified.

Here are the first lines of the same attachment for a client ( which is broken ), and me ( which works ):

GOOD:

--_009_f41fd9fdca564a38a20ef3d6bf06fb16MBX10BIAD3mex06mlsrvrco_
Content-Type: application/pdf; name="report.pdf"
Content-Description: report.pdf
Content-Disposition: attachment; filename="report.pdf"; size=12318;
	creation-date="Thu, 02 Jan 2020 17:19:11 GMT";
	modification-date="Thu, 02 Jan 2020 17:19:11 GMT"
Content-Transfer-Encoding: base64

JVBERi0xLjQKJeLjz9MKMiAwIG9iago8PC9MZW5ndGggNDkvRmlsdGVyL0ZsYXRlRGVjb2RlPj5z
dHJlYW0KeJwr5HIK4TI2UzA3NVMISeFyDeEK5CpUMFQwAEIImZyroB+RZqjgkq8QyAUA6zkJ9gpl
bmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZS9QYWdlL01lZGlhQm94WzAgMCA2MTIgNzky
XS9SZXNvdXJjZXM8PC9YT2JqZWN0PDwvWGYxIDEgMCBSPj4+Pi9Db250ZW50cyAyIDAgUi9QYXJl


BAD:

--=_197768b9c33516275f4425eb38bc757c
Content-Transfer-Encoding: base64
Content-Type: application/pdf;
 name=report.pdf;
 charset=UTF-8
Content-Disposition: attachment;
 filename=report.pdf

JVBERi0xLjQKJeLjz9MKMiAwIG9iago8PC9MZW5ndGggNDkvRmlsdGVyL0ZsYXRlRGVjb2RlPj5z
dHJlYW0KeJwr5HIK4TI2UzA3NVMISeFyDeEK5CpUMFQwAEIImZyroB+RZqjgkq8QyAUA6zkJ9gpl
bmRzdHJlYW0KZW5kb2JqCjQgMCBvYmoKPDwvVHlwZS9QYWdlL01lZGlhQm94WzAgMCA2MTIgNzky
XS9SZXNvdXJjZXM8PC9YT2JqZWN0PDwvWGYxIDEgMCBSPj4+Pi9Db250ZW50cyAyIDAgUi9QYXJl

I can identify if the attachment has a charset, but I'm not sure what to do to convert it the same as all the other inbound emails that work:

            $charset = "Unknown";
            if ( $attachment->getHeaderParameter('Content-Type', 'charset') ) {
                $charset = $attachment->getHeaderParameter('Content-Type', 'charset');
            }
            print("CharSet for " . $name . " is " . $charset . "\n");

**Comment by zbateson** [comment]
Aah, yeah that would do it.

I have a built-in assumption that if a mime part defines a charset, to assume the content is "text" rather than binary data.  You can see that wonderful line here:

https://github.com/zbateson/mail-mime-parser/blob/e97dd4f1d39002503f001af949a6c6bfec39da37/src/Message/Part/MimePart.php#L71

The reason why is to handle charset conversion when necessary, but I guess that ideas been proven wrong and it can happen anyway.  I'm not sure at this point if I should change that and to what though, so I'll keep this in mind.

For your case, I recommend a different change though.  Instead of identifying that the attachment has a charset and doing something, just change how you're reading the stream assuming you *know* and are always only reading binary data like a pdf... in that case you can call one of these:

``` $attachmentPart->getBinaryContentResourceHandle() ``` or ``` $attachmentPart->getBinaryContentStream() ``` depending on how you're reading attachment data.

**Comment by zbateson** [comment]
I think in retrospect, 'getBinaryContentStream()' or 'getBinaryContentResourceHandle()' should be used in situations like these.  Using the 'getContent()' methods detect the presence of a charset parameter, and try to convert the stream to utf-8. They should only really be used if that's desirable.
