### ISSUE TITLE
Issue with setRawHeader / addRawHeader

### ISSUE THREAD

**Issue by postme** [zbateson/mail-mime-parser#107]
Hi there Zaahid, hope you're doing well!

I ran into an issue with setRawHeader / addRawHeader today, I hope you can shed some light on the behaviour and what I'm doing wrong?

Case in question is that I want to add multiple headers with the same name to an email. The code states that I either use setRawHeader with an offset or use addRawHeader. However both functions only add the first occurence of the header and no subsequent occurences are added to the header.

Code in question:

```
$atts = $email->getAllAttachmentParts();
    if (!empty($atts)) {
        $tmpKey = getRandomFilename();

        foreach ($atts as $index => $part) {
            $filename = $part->getHeaderParameter(
                'Content-Type',
                'name',
                $part->getHeaderParameter(
                    'Content-Disposition',
                    'filename',
                    '__unknown_file_name_' . $index
                )
            );

            if (isset($filename)) {
                $body = $part->getContent(); 
                file_put_contents('/tmp/' . $filename, $body);
                $email->removeAttachmentPart(0);
                $documentReference = urlencode('https://' . ATTACHMENT_URL . '/' . $tmpKey) . ';FileName=' . urlencode($filename) . ';ProviderType=OneDriveConsumer; Permission=AnonymousRead; Content-Type=' . mime_content_type('/tmp/' . $filename);
                unset($body);
                unlink('/tmp/' . $filename);
                $email->setRawHeader('Document-Reference', $documentReference, $index);
            }
            unset($filename);
        }
```

I'm using mailmimeparser version 1.2.0

The resulting document only contains one 'Document-Reference' header and it's always the first attachment that is referenced.

Logging shows that a test email with 2 attachments has both attachments recognized yet only the first attachment (test10Mb.db) is added as a Document-Reference header.

```
Info: Secumail\setAttachmentLinks: Start
Info: getRandomFilename: Start
Info: getRandomFilename: Done
Info: Secumail\setAttachmentLinks: $index: 0
Info: Secumail\setAttachmentLinks: $filename: test10Mb.db
Info: Secumail\setAttachmentLinks: $documentReference: https%3A%2F%2Fattachment.secumail.nl%2F2bqzo221kf6so8sk0okg0k844kwc88ow4g0ogo4sso8cocsgs88kws8488woco;FileName=test10Mb.db;ProviderType=OneDriveConsumer; Permission=AnonymousRead; Content-Type=application/octet-stream
Info: Secumail\setAttachmentLinks: $index: 1
Info: Secumail\setAttachmentLinks: $filename: test1Mb.db
Info: Secumail\setAttachmentLinks: $documentReference: https%3A%2F%2Fattachment.secumail.nl%2F2bqzo221kf6so8sk0okg0k844kwc88ow4g0ogo4sso8cocsgs88kws8488woco;FileName=test1Mb.db;ProviderType=OneDriveConsumer; Permission=AnonymousRead; Content-Type=application/octet-stream
```

I've also tried using addRawHeader:

```
$email->addRawHeader('Document-Reference', $documentReference);
```

But that didn't make any difference.

Any idea what I'm doing wrong?

Kind regards
Meint

**Comment by postme** [comment]
hmm a separate test case outside of my main logic does show 2 headers inserted so it looks like the issue is elsewhere, I will close this case as the issue is not with setRawHeader / addRawHeader after all.

**Comment by zbateson** [comment]
Nice to hear from you and see you're still using the library all the same :)

All the best!

**Comment by postme** [comment]
Hi zaahid yeah still going strong, my business is doing well and growing, thanks to mailmimeparser. The issue above was caused by a difference in library version, I had two lambdas running on the old 0.4 version which can't handle multiple similar headers, hence the issue!

**Comment by zbateson** [comment]
Wonderful!  I've 90% completed a version with built-in encryption/decryption as well which might be of use to you and others... I did most of the work a while ago in zbateson/gpg-interface zbateson/gpg-pear and zbateson/gpg-php but then life happened and now I'm a dad.  The rest coming some time this year hopefully in a 2.0 release.
