### ISSUE TITLE
How to set attachment name with special characters ? 

### ISSUE THREAD

**Issue by mvnaz** [zbateson/mail-mime-parser#112]
Here the versions of components:

```
zbateson/mail-mime-parser                        1.1.8              MIME email message parser
zbateson/mb-wrapper                              1.0.0              Wrapper for mbstring with fallback to iconv for encoding conversion and string manipulation
zbateson/stream-decorators                       1.0.2              PHP psr7 stream decorators for mime message part streams
```

I add attachment like this:

```
$this->parsedMail->addAttachmentPart($handle, $mimeType, $filename);
$mime = (string) $this->parsedMail;
```

and problem is when name consists special chars like cyrillic or other - they get replaced with '?'

I also tries to convert filename like this:

`$filename = "=?UTF-8?B?" . base64_encode($filename);`

But then attachment appears in inbox with wrong name like:

`=?UTF-8?B?aWJhbiDlm57lpI3vvJrlm57lpI0g0J/QldCU0KDQmNC80J4hIS5qcGVn`

Here is example of attachment header before and after I modified it with MailMimeParser:

Original:

```
Content-Type: image/jpeg; name="=?UTF-8?B?aWJhbiDlm57lpI3vvJrlm57lpI0g0J/QldCU0KDQmNCb?=
	=?UTF-8?B?0J4hIS5qcGVn?="
Content-Disposition: attachment;
	filename="=?UTF-8?B?aWJhbiDlm57lpI3vvJrlm57lpI0g0J/QldCU0KDQmNCb0J4hIS5qcGVn?="
Content-Transfer-Encoding: base64
Content-ID: <f_k7g2opvo0>
X-Attachment-Id: f_k7g2opvo0
```

After:

```
Content-Transfer-Encoding: base64
Content-Type: image/jpeg;
	name="=?UTF-8?B?aWJhbiDlm57lpI3vvJrlm57lpI0g0J/QldCU0KDQmNCb0J4hIS5qcGVn"
Content-Disposition: attachment;
	filename="=?UTF-8?B?aWJhbiDlm57lpI3vvJrlm57lpI0g0J/QldCU0KDQmNCb0J4hIS5qcGVn"
```

I need to attach files with names consist different characters.. How can I solve it?

**Comment by mvnaz** [comment]
`$filename = "=?UTF-8?B?" . base64_encode($filename) . "?=";`

The above solution works! But how do you think, is it good idea ? And will it work for all cases and imap servers ?

**Comment by zbateson** [comment]
Hi @mvnaz ,

the mail-mime-parser project only offers very basic 'write' functionality -- the tools are there, but you're left on your own to figure out format, encoding, etc...

At some point in the future I may expand on that functionality, but it's not in my current plans as there are still areas of the parser I want to expand on (like encryption support).

All the best.
