### ISSUE TITLE
Mail Sent By Outlook Not Showing HTML

### ISSUE THREAD

**Issue by swartjie** [zbateson/mail-mime-parser#117]
Hey Guys,

Can you please advise. I've got a mail being sent by outlook, which is set to format as HTML, but it seems the email includes some XML tags aswell.

This I assume causes the getHtmlContent() to return NULL, but you can get the content as text though...
How can I get the HTML encoded version?
Even if I get it raw, i'd like to make a few changes via search and replace and then inject it as is back so I don't really care what formatting outlook sent it in...

If I can cleanly convert it to HTML, that would be first prize!

**Comment by zbateson** [comment]
Hi @swartjie -- a sample email with the issue could help.

I can say generically though that the parser doesn't look at body content to determine the content type of a part, and only uses header info.  So I'm guessing it's not identifying a part as being 'text/html' in the body of the email for whatever reason.

**Comment by zbateson** [comment]
Please reopen if this is still an issue and there's additional info to be shared.
