### ISSUE TITLE
Use `const`s for header names?

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#121]
Was it an intentional decision that you use strings for the header names `->getHeader('from') ` and not constants `->getHeader(Header::FROM)` or even classes `->getHeader(FromHeader::class)`?

I know that you can't set up a `const` for any `X-Whatever` header ;-) But since you process different headers differently (see https://github.com/zbateson/mail-mime-parser/tree/master/src/Header), wouldn't it be a good idea to give users a hint about this, by definiing `const`s for all standard headers?

Besides, I'm always unsure how to spell `Message-ID` ;-)

**Comment by zbateson** [comment]
I wouldn't say intentional either way really, I can see some value in having a const so there's error checking on it :)

**Comment by ThomasLandauer** [comment]
Implemented in https://github.com/zbateson/mail-mime-parser/pull/126
