### ISSUE TITLE
Remove header name from `->getHeader()`

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#123]
Is there a limit for issues per day? ;-)

I think that the main function for reading a header (i.e. `->getHeader()`) should return just the value/content, not the header name:

If this is in the email
```
From: company@example.com
```
`->getHeader('from')` now returns (see [`AbstractHeader::__toString()`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Header/AbstractHeader.php#L131)):
```
From: company@example.com
```
but should return:
```
company@example.com
```
Why?
* Semantics: The string `From:` is not part of the information
* Pragmatics: If I ask for the `From` header, there's no need to prefix the answer with something like "Here comes the `From` header". And if I store it in a database (in a column probably called `from`), there's no need to store "From:" over and over.

I think it's a good idea to do have a function that returns the full line, it just shouldn't be the "main" function. Maybe something like `getFullHeader()`? Speaking of naming: What was your idea behind `->getHeaderValue()`? For e.g. the `Subject` this would be what I'm asking for here, but for `From` it just returns the email address, not the person's name.

And I spotted a (somewhat related) inconsistency in `README.md`: `getPersonName()` vs. `getName()`:
```php
echo $message
    ->getHeader('from')                         // AddressHeader
    ->getPersonName();                          // Person Name
echo $message
    ->getHeader('to')                           // also AddressHeader
    ->getAddresses()[0]                         // AddressPart
    ->getName();                                // Person Name
```
The former is a method of [`AddressHeader`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Header/AddressHeader.php#L122). But since the latter is a method of the more generic [`ParameterPart`](https://github.com/zbateson/mail-mime-parser/blob/master/src/Header/Part/ParameterPart.php#L58), you probably cannot change it in the code?

**Comment by zbateson** [comment]
I disagree with this one, although there may be less use for a user looking at the entire header, the object itself doesn't care that you called ``` getHeader('from') ```, and in this case the __toString is telling you about the whole object you're looking at... essentially "this is the String representation of this object"... i.e. __toString.

It's also used when writing out an email, essentially the "string" representation of a Message is all the headers and body... I don't assume that because you're looking at a Message you know that the Subject is X, that you're only interested in the text content, etc..., etc..., I'm assuming __toString should give the "string" representation of whatever object it is you're looking at.

This may not be consistent in every project, etc... but I think it makes the most sense.  If you only want a specific part of it, you'd call $message->getTextContent or $header->getSomethingSpecific, etc....

**Comment by ThomasLandauer** [comment]
I see what you mean by "string representation of the object". However, if I have a `Person` entity, my `__toString()` looks like this:
```php
return $this->getFirstName() . $this->getLastName();
```
not like this:
```php
return 'Person: ' . $this->getFirstName() . $this->getLastName();
```

> you'd call $header->getSomethingSpecific, etc....

But there just is no function that gives me the entire header without the name-prefix! (That's what I'm saying) Or is it?

**Comment by zbateson** [comment]
>  However, if I have a Person entity, my __toString() looks like this

Yes, but this not an "Address" entity, it's an "AddressHeader" entity, this makes sense to me.  You can echo $message; and get the whole message (which internally calls __toString() on each header, so you can change headers and the whole message will get written out cleanly for example).

It certainly wouldn't make sense to put "Person: " in front of some random Person object's "__toString", but if it were PersonHeader as part of a mime object, the name of which is "Person", then I think it would :smile: 

In another ticket I proposed maybe ``` $header->getDisplayValue ``` that could be written to do something like that potentially?

**Comment by ThomasLandauer** [comment]
> You can echo $message; and get the whole message (which internally calls __toString() on each header, so you can change headers and the whole message will get written out cleanly for example)

Since you mentioned this repeatedly: Is there a use-case for this? I mean, this is an email parser, not an email creator. So if I want to see the entire message, I can take a look at what I passed into `$mailParser->parse();` :-)

**Comment by ThomasLandauer** [comment]
> and do what you will with it after.

But you can't send it? Or can you?

**Comment by zbateson** [comment]
There's nothing in zbateson/mail-mime-parser to help with sending emails.

**Comment by ThomasLandauer** [comment]
I still think that the `Header`s main string representation (i.e. `__toString()`) should not include the header name. Your argument

> You can echo $message; and get the whole message (which internally calls __toString() on each header

...doesn't convince me since the very sense of an email parser is to look at single parts/headers, not at the entire message. However, I'm closing this in favor of https://github.com/zbateson/mail-mime-parser/issues/122, since changing the current behavior only makes sense as part of a larger overhaul of the nomenclature, which we're discussing there.
