### ISSUE TITLE
"Double" encoded headers

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#131]
Just wanted to share what I just encountered in the wild (German company, this time ;-)

* Let's start with our well-known `foobär`
* Now quoted-printable encode it: `=?utf-8?Q?foob=C3=A4r?=`
* Now add some more text: `Re: =?utf-8?Q?foob=C3=A4r?= one two three`
* Ready for the fun part? base64-encode it!!: `=?utf-8?b?UmU6ID0/dXRmLTg/UT9mb29iPUMzPUE0cj89IG9uZSB0d28gdGhyZWU=?=`

There you go:
```
Subject: =?utf-8?b?UmU6ID0/dXRmLTg/UT9mb29iPUMzPUE0cj89IG9uZSB0d28gdGhyZWU=?=
```

Your `$message->getHeader('subject')->getValue()` returns:
```
Re: =?utf-8?Q?foob=C3=A4r?= one two three
```

But php-mime-mail-parser's [`$parser->getHeader('subject')`](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/release-6.0.0/src/Parser.php#L251) just decodes it:
```
Re: foobär one two three
```

**Comment by zbateson** [comment]
How does Thunderbird handle it?

php-mime-mail-parser's ability to handle it might be a side-effect of how it's handling headers generally, and may not be intentional.  Anyway, as discussed elsewhere it's not a gauge as its goals are different, etc... etc...

**Comment by ThomasLandauer** [comment]
Thunderbird's email window shows the same as you:
```
Re: =?utf-8?Q?foob=C3=A4r?= one two three
```
In the overview window (i.e. list of emails) I haven't checked.

**Comment by zbateson** [comment]
Yeah, in addition having "=?utf-8?Q?foobar?= in a subject is valid... I'm allowed to discuss mime headers in an email's subject, aren't I? :tea: :stuck_out_tongue_closed_eyes:

**Comment by ThomasLandauer** [comment]
So you're saying that having a character sequence like `=?utf-8?....` in the subject is not illegal. But the correct behavior is to just encode the "outer" encoding (and not look for further stuff to decode inside of it)?

I'm closing this, since it's nothing you should change.

**Comment by zbateson** [comment]
Correct :)
