### ISSUE TITLE
Trim final `=` from quoted-printable encoded text/plain body

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#132]
If the message body's text/plain part *ends* with:
```
Bye, Thomas

=
```
your `$message->getTextContent()` is preserving the final `=`, while php-mime-mail-parser's [`$parser->getMessageBody('text')`](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/release-6.0.0/src/Parser.php#L393) is removing it. Thunderbird is removing it too.

Adding such a final `=` seems to be quite common, I'm seeing it in around 2-5% of the emails I'm analyzing.

I haven't looked at some specs, but since `=` is the escape character, it sounds reasonable to remove it :-)

**Comment by zbateson** [comment]
I wonder if I'm erroneously trimming a final "\r\n" before passing it to quoted_printable_decode or something.  It would be something in here most likely: https://github.com/zbateson/stream-decorators/blob/master/src/QuotedPrintableStream.php 

Could you tell me if this is part of a multipart message, or if that's the entire message body that you pasted and confirm that there is an "\r\n" following the "=" in an email you found this happening in?  A more complete example might help, particularly with multipart messages, because the final \r\n *I think* belongs to the multipart boundary.

**Comment by ThomasLandauer** [comment]
* All are multipart (except for a handful, which look like spam at first glance)
* From those passing the regex `=\s*$`, 98% are also passing `=\n+$`. So yes, there is a final line break (the `\r` maybe just got lost somehow).
* The few I've actually opened do have this `=` also after their HTML part. (I didn't mention this right away, cause since it's after the `</html>` it doesn't matter much.) Do you want me to check for how many this is true?
* Example: It's hard to find a "typical" example. But you can ask more concrete questions!

**Comment by zbateson** [comment]
Thanks again @ThomasLandauer -- I think I found the issue.

I put up a fix in dev-master on zbateson/stream-decorators, would you be able to give that a shot and let me know if that fixes it?

**Comment by zbateson** [comment]
It's a change on this line if that makes it easier to test directly (instead of fuddling with composer): https://github.com/zbateson/stream-decorators/blob/e322ec4f2068430a32434c21a6f8974ba2d79e56/src/QuotedPrintableStream.php#L93

**Comment by ThomasLandauer** [comment]
In short: Yes, that fixes it! :-)

In long: Before, 3.8% of all mails were passing the regex `=\n+$`. With your changed line, this dropped to 0.007%. Also, I have some mails ending with a full line of `=` (not included in the numbers above), and those are still there - so you're not removing too much.
As said above, I'm only looking at `$message->getTextContent();`, so I can't say what's happening at the HTML part.

**Comment by zbateson** [comment]
Hmm, it should remove instances of "=" at the end of any line including the last one.

> Also, I have some mails ending with a full line of =

So do you mean there's still an issue?  As-in, you have something like:

```
Email body
=
More email
```

Using 'quoted-printable' encoding, and the '=' is coming out as-is?

**Comment by ThomasLandauer** [comment]
Sorry for the confusion!

What I have is an email ending with:
```
Bye,
Thomas
======================================
```
And those `=`s are preserved. So everything's fine! :-)

**Comment by zbateson** [comment]
Excellent, fix is on master now and will be included in next release :smile_cat:

**Comment by ThomasLandauer** [comment]
I'm closing this, since it looks resolved to me :-)
