### ISSUE TITLE
Check if "undeclared" encoding is really not UTF-8 before converting it to UTF-8

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#133]
When I have an email body which is in fact UTF-8 but the email lacks any `charset` declaration, you treat is as ASCII and *encode* it to UTF-8. Which is in sync with [RFC 2045](https://tools.ietf.org/html/rfc2045#section-5.2):

> Default RFC 822 messages without a MIME Content-Type header are taken by this protocol to be plain text in the US-ASCII character set

So `$message->getTextContent()` gives me something like:
```
fÃ¶Ã¶bÃ¤r
```
Thunderbird does the same. However, php-mime-mail-parser's [`$parser->getMessageBody('text')`](https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/release-6.0.0/src/Parser.php#L393) keeps it as-is:
```
fööbär
```

I'm "fixing" this in my code by checking: When I `utf8_decode()` your output (i.e. "reverse" the conversion you did automatically), is it still UTF-8?:
```php
if (mb_check_encoding(utf8_decode($message->getTextContent()), 'UTF-8'))
{
    $text = utf8_decode($message->getTextContent());
}
else
{
    $text = $message->getTextContent();
}
```

**Comment by zbateson** [comment]
I recommend overriding the default charset in use in that case:

```php
$message->getHtmlPart()->setCharsetOverride('utf-8');
echo $message->getHtmlContent();
```
You can read more about default charsets here: https://github.com/zbateson/mail-mime-parser/issues/110

**Comment by ThomasLandauer** [comment]
That won't work in that case, cause *in advance* I don't know the charset either ;-)

**Comment by zbateson** [comment]
Yup, there's no easy fix.  If you want to use mb_check_encoding yourself though, you're free to do so.  There's no 'good way' of knowing if a charset is 'something' without some indication though, all that function does is check that bytes within the passed string 'pass' as the charset you give it, it doesn't know if that's the original charset.

**Comment by ThomasLandauer** [comment]
Yes, indeed. As far as I see it, `mb_check_encoding()` just checks if each byte (or byte sequence) is a formally valid character. So `mb_check_encoding('fÃ¶Ã¶bÃ¤r', 'UTF-8')` returns `true`. The only thing that `mb_check_encoding()` saves you from is totally invalid characters, as mentioned at https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/329

So I'm no longer using the code I posted here. Therefore I'm closing this.
