### ISSUE TITLE
Remove `->parse()` and do it in the constructor / new object for every parsed email

### ISSUE THREAD

**Issue by ThomasLandauer** [zbateson/mail-mime-parser#135]
When I do:
```php
$mailParser = new MailMimeParser();
$message = $mailParser->parse($email1);
$message = $mailParser->parse($email2);
echo $message->getHeaderValue('subject');
```
... I would be afraid that if `$email2` doesn't have a subject (or parsing fails or whatever), I'd get back `$email1`s subject ;-)

Am I seeing it right that `->parse()` always needs to be called first, before any other function works? If yes, I suggest to remove `parse()` in favor of a mandatory constructor argument:
```php
$message = new MailMimeParser($email);
```
With the reason: This is an email parser, so if you don't have an email, don't call it :-)

**Comment by zbateson** [comment]
You're constructing an instance of a parser, and able to call a parse function on it returning a Message object.  You're definitely misreading that.

It allows you to use the parser as a dependency if you're using dependency injection.

The shorthand method if you're not, is Message::from.

**Comment by ThomasLandauer** [comment]
This was just some gut feeling - maybe it's wrong. Since it obviously doesn't make sense to you, I'm closing it :-)
