### ISSUE TITLE
empty utf8 quoted not parsed correctly

### ISSUE THREAD

**Issue by markusramsak** [zbateson/mail-mime-parser#160]
This is the simplified original version of the email.
At the line beginning with "To:" there is an expression "=?utf-8?Q??=" which should simply be parsed to an empty string.
Instead it keeps as it is.

Please parse **=?utf-8?Q??=** to an empty string.

```
Delivered-To: notimportant@gmail.com
Date: Thu, 10 Sep 2020 09:29:57 -0400
To: =?utf-8?Q??= <receiver@gmail.com>
From: From <from@gmail.com>
Subject: Newsletter
Message-ID: <SEMA-CR-1-1EMM4XDXI@gmail.com>
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: Quoted-Printable
```

**Comment by zbateson** [comment]
Top of my head, this should just be a matter of changing the regex pattern for the mime-encoded part matcher to use a '*' instead of '+' for matching.
