### ISSUE TITLE
getHtml or gettextContent() returns null

### ISSUE THREAD

**Issue by sticcino** [zbateson/mail-mime-parser#168]
Hi,
just started using the library and is working nicely.

tested with an .eml file and the getHtmlContent() function returned the data correctly.

then tried with an outlook .msg file.
its returning the correct to/from/cc/subject without issue, but does not return the message content either getText or getHtmlContent() -- everything is empty

not sure where to start to investigating at.

Thanks,

**Comment by zbateson** [comment]
Hi @sticcino --

"msg" is a proprietary Microsoft format, it's not a raw 'mime' message (and therefore not readable by this library).

All the best

**Comment by sticcino** [comment]
appreciated, thanks for the explanation
