### ISSUE TITLE
Long filenames with single quotes appear to be unparsable.  

### ISSUE THREAD

**Issue by murphatron** [zbateson/mail-mime-parser#182]
Hello! We're utilizing this package to parse and display MIME messages we have in storage to the user. I'm encountering an error that occurs when the package attempts to parse an attachments `Content-Disposition` header with a filename utilizing parameter value continuation.

The header set for the attachment part looks like:  
```
Content-Disposition: attachment;
	filename*0="1 Neuropathy 'Trick' Reverses Diabetic Nerve Pain? -Try Tonight.";
	filename*1=eml
Content-Type: message/rfc822;
	name="1 Neuropathy 'Trick' Reverses Diabetic Nerve Pain? -Try Tonight.eml"
Content-Transfer-Encoding: binary
```

And the reported error is:  
```
iconv(): Wrong charset, conversion from `1 Neuropathy ' to `UTF-8//TRANSLIT//IGNORE' is not allowed
```

As you can see, the sender is forwarding an attached spam email which is resulting in this break. From what I can tell, it's the single quotes that seem to be creating the invalid assumption that the "1 Neuropathy " string segment is a charset and "Trick" string segment is the language.

**Comment by zbateson** [comment]
Fixed and released in 2.0.1 and 1.3.3.
