### ISSUE TITLE
PHP 8.1 deprecation notices

### ISSUE THREAD

**Issue by alexei-bykovski** [zbateson/mail-mime-parser#194]
Hello. I use the last version of lib 2.2.1 and have deprecation notices.

1. Method "SplSubject::attach()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\MessagePart" now to avoid errors or add an explicit @return annotation to suppress this message.
2. Method "SplSubject::detach()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\MessagePart" now to avoid errors or add an explicit @return annotation to suppress this message.
3. Method "SplSubject::notify()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\MessagePart" now to avoid errors or add an explicit @return annotation to suppress this message.
4. The "ZBateson\MailMimeParser\Message::setHtmlPart()" method will require a new "string $contentTypeCharset" argument in the next major version of its interface "ZBateson\MailMimeParser\IMessage", not defining it is deprecated.
5. Method "SplObserver::update()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Parser\Part\ParserPartStreamContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
6. Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\PartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
7. Method "ArrayAccess::offsetGet()" might add "mixed" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\PartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
8. Method "ArrayAccess::offsetSet()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\PartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
9. Method "ArrayAccess::offsetUnset()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Message\PartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
10. Method "ArrayAccess::offsetExists()" might add "bool" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Parser\Part\ParserPartChildrenContainer" now to avoid errors or add an explicit @return annotation to suppress this message.
11. Method "SplObserver::update()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\MailMimeParser\Stream\MessagePartStream" now to avoid errors or add an explicit @return annotation to suppress this message.
12. Method "Psr\Http\Message\StreamInterface::close()" might add "void" as a native return type declaration in the future. Do the same in implementation "ZBateson\StreamDecorators\NonClosingStream" now to avoid errors or add an explicit @return annotation to suppress this message.

Could you please fix all these notices please? Thank you.

**Comment by zbateson** [comment]
Hi @alexei-bykovski --

If you feel like submitting a pull request with "@return" annotations to fix it, I'd approve it.  Otherwise, not entirely sure when I'll get around to this.

All the best

**Comment by zbateson** [comment]
Yeah, that would be great, thank you!

**Comment by alexei-bykovski** [comment]
Hi @zbateson. Please merge pull request https://github.com/zbateson/mail-mime-parser/pull/197. Thank you.

**Comment by alexei-bykovski** [comment]
Merged
