### ISSUE TITLE
Email adress with quoted local part has quotes truncated

### ISSUE THREAD

**Issue by mcerva** [zbateson/mail-mime-parser#203]
Example of an email address which is valid according to https://en.wikipedia.org/wiki/Email_address#:~:text=example.org.-,Examples,-%5Bedit%5D

`From: "john.no.doe."@doe.no.jp`

`AddressHeader->getEmail()` returns `john.no.doe.@doe.no.jp` which is invalid as quotes are missing.

**Comment by zbateson** [comment]
That's a very good point.  Thanks for that :)

Fix will come soon.

**Comment by zbateson** [comment]
Released in 2.3.0
