### ISSUE TITLE
Invalid resource type: object

### ISSUE THREAD

**Issue by VarroReve** [zbateson/mail-mime-parser#204]

**Comment by zbateson** [comment]
Hi there,

Please leave a detailed description/recreation steps if this is an issue to reopen this.

**Comment by VarroReve** [comment]
In laravel 9.1 `SwiftMailer` has been replaced by `SymfonyMailer`

Which In my case, I encountered something like:
```
use ZBateson\MailMimeParser\Message;

// $email is instance of \Symfony\Component\Mime\Email
Message::form($email, true);
```

Can I use `Messages` to parse a `\Symfony\Component\Mime\Email` object?

**Comment by VarroReve** [comment]
Sorry, I was being stupid, close it now.
