### ISSUE TITLE
docs wrong way of getting sender name?

### ISSUE THREAD

**Issue by boynet** [zbateson/mail-mime-parser#221]
the [docs](https://mail-mime-parser.org/) saying this to get info about the sender:
```
$from = $message->getHeader('From');
$fromName = $from->getName();
$fromEmail = $from->getEmail();
```

but `$fromName` will just be 'From' as the getName is getting the name of the header at least in my case
I believe it suppose to be `$from->getPersonName()`

**Comment by zbateson** [comment]
Right you are, thanks for that.  Fixed it :)
