### ISSUE TITLE
phpstan complains about method getAddresses

### ISSUE THREAD

**Issue by postme** [zbateson/mail-mime-parser#223]
Hi Zaahid,

Code in question:

`
            $toAddresses = $email->getHeader('To');
            foreach ($toAddresses->getAddresses() as $address) {
                $toName = $address->getName();
                $toEmail = $address->getEmail();
            }
`

phpstan complains:

`Cannot call method getAddresses() on ZBateson\MailMimeParser\Header\IHeader`

Adding getAddresses to IHeader.php interface file fixes the issue in phpstan but generates a different issue in the code 

`PHP Fatal error:  Class ZBateson\MailMimeParser\Header\GenericHeader contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (ZBateson\MailMimeParser\Header\IHeader::getAddresses)`

Any way to resolve the issue and make phpstan happy??
Meint

**Comment by zbateson** [comment]
Hi @postme ,

Aah, sounds good!  I had replied on the pull request about this instead of here, hope you saw that and it helped :)
