### ISSUE TITLE
cid mismatch - attachement

### ISSUE THREAD

**Issue by orion3dgames** [zbateson/mail-mime-parser#227]
Hi, 

First, thanks for you great & useful project,

I'm having some issues with some emails that have CID mismatch in the attahchment versus the HTML content, for ex: 
- HTML will show <img src="cid:image002.png@01DA3247.90F05FB0" alt="">
- ATTACHMENT getContentId() will show:  image980291.png@2EBB4CDB.C08FCC21
The issue is that I cannot update the HTML with the updated attachement url because I have no way to knowing what html part to update like this: 
```str_replace("cid:".$attachment->content_id, 'URL HERE', $content_html);```

any ideas what I'm doing wrong?

Thanks,

**Comment by zbateson** [comment]
Sorry, sounds like a generic php question (please post to stackoverflow.com) and not related to issues using mail-mime-parser.

Feel free to reopen if there's a bug or issue though.

All the best
