### ISSUE TITLE
Possible memory leak when parsing mails in a loop

### ISSUE THREAD

**Issue by t0maash77** [zbateson/mail-mime-parser#231]
Hello, I recently discovered that the library seems to be leaking memory when used to parse multiple emails in a loop.

```php
<?php declare(strict_types=1);

use ZBateson\MailMimeParser\Message;

echo "Memory usage before: " . (memory_get_usage() / 2**20) . PHP_EOL;
echo "Memory peak usage before: " . (memory_get_peak_usage() / 2**20) . PHP_EOL;

$i = 0;
while ($i++ < 100) {
    $message = Message::from('whatever-string-content', true); //doesn't matter if attached param is true or false
    unset($message);

    $usage = round(memory_get_usage() / 2**20, 2);

    echo 'Current memory usage: ' . $usage . ' MB' . PHP_EOL;
}

echo "Memory usage after: " . (memory_get_usage() / 2**20) . PHP_EOL;
echo "Memory peak usage after: " . (memory_get_peak_usage() / 2**20) . PHP_EOL;
```

Playground with the issue replicated: https://play.phpsandbox.io/zbateson/mail-mime-parser/oqy8M5NeDDKGABzl

I'm always passing the contents of the message as a string to Message::from() factory. From what I've tested, it's the same using the other approach, e.g.: https://play.phpsandbox.io/zbateson/mail-mime-parser/mN7g4E117xEWn281

I found a "fix" to this, by calling `gc_collect_cycles()` in the loop after instantiating the message:

```php
<?php declare(strict_types=1);

use ZBateson\MailMimeParser\Message;

$i = 0;
while ($i++ < 100) {
    // ... do everything as before

    gc_collect_cycles(); // -> With this at the end of the loop the issue is solved
}
```
Is this correct behaviour? Thanks a lot.

**Comment by zbateson** [comment]
Hi @t0maash77 --

Yeah, that's just how "safe" languages work.  Internally when you delete an object the memory isn't recovered till garbage collection deems it necessary to happen (or you manually instruct it to).

All the best,
Zaahid
