### ISSUE TITLE
HELP: Getting the email from the forwarded email 

### ISSUE THREAD

**Issue by vincent-goossens** [zbateson/mail-mime-parser#236]
Hi, I am parsing a mime email and wanted to retrieve the From/De from the forwarded email in this case (the-email-i-want@the-email-i-want.com)

in the email body I have something like this:

`--0000000000005a156b0616230ff8
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

---------- Forwarded message ---------
De: Marc POUPARD <the-email-i-want@the-email-i-want.com>
Date: mi=C3=A9, 21 feb 2024 a las 17:58
Subject: some-other-email-subject
To: some-other-email-name <some-other-email@some-other-email>

Hi..,`

Any suggestion to get this without parsing this some how?

I was looking to the header Resent-To, that sounds what I want, but is empty

**Comment by zbateson** [comment]
Hi @vincent-goossens 

For general usage help, please post to StackOverflow so people can help you with your question.  For issues/bugs/feature requests feel free to post here :)

All the best
