### ISSUE TITLE
AddressHeader missing spaces between encoded words 

### ISSUE THREAD

**Issue by 0xb4lint** [zbateson/mail-mime-parser#244]
I've encoded an address containing special characters and **double space** with `Symfony\Component\Mime\Address` and it resulted two "encoded-word"s (RFC2047) header:
input: `To: fóó  bár <test@example.com>`
output: `To: =?utf-8?Q?f=C3=B3=C3=B3?=  =?utf-8?Q?b=C3=A1r?= <test@example.com>`

The encoded string is parsed with `ZBateson\MailMimeParser\Header\AddressHeader` results the following name: `fóóbár`, the double spaces are missing.

Test https://github.com/0xb4lint/mail-mime-parser/commit/2c22d4f9803a6e973573ac886f70d8c8a2f04098 result:
```
1) ZBateson\MailMimeParser\Header\AddressHeaderTest::testMultipleEncodingSingleAddress
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'fóó  bár'
+'fóóbár'
```
If the `AddressHeader` extends `MimeEncodedHeader`: https://github.com/0xb4lint/mail-mime-parser/commit/3bf2acbe0939eadfef84f39c6e72f0f5c858d7b1 there's space but not double:
```
1) ZBateson\MailMimeParser\Header\AddressHeaderTest::testMultipleEncodingSingleAddress
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'fóó  bár'
+'fóó bár'
```

**Comment by zbateson** [comment]
Hi @0xb4lint -- Sorry thought I responded already!

That's correct and expected -- spaces between two RFC2047 encoded parts must be ignored, and must be in the encoded token itself.

From [section 6.2](https://datatracker.ietf.org/doc/html/rfc2047#section-6.2):

> When displaying a particular header field that contains multiple
   'encoded-word's, any 'linear-white-space' that separates a pair of
   adjacent 'encoded-word's is ignored.  (This is to allow the use of
   multiple 'encoded-word's to represent long strings of unencoded text,
   without having to separate 'encoded-word's where spaces occur in the
   unencoded text.)

You can see that same thing happening here if you put your encoded "to" header in: https://dogmamix.com/MimeHeadersDecoder/

I'm a bit confused that it was generated that way if you're using a library, is it an issue with Symfony\Component\Mime\Address that you found?  Can you confirm if you tried to open your mail in a mail client and it displayed correctly?

All the best!

**Comment by 0xb4lint** [comment]
Hi @zbateson!

Thanks for the detailed response, it seems like you're right!

I've created a basic example:
https://github.com/0xb4lint/mime-address-issue/blob/main/index.php

And added some mail client screenshots:
https://github.com/0xb4lint/mime-address-issue/tree/main/client-screenshots

`Symfony\Component\Mime` [generated](https://github.com/0xb4lint/mime-address-issue/blob/main/output.eml) the following header with double spaces (from `fóó  bár`): 
`From: =?utf-8?Q?f=C3=B3=C3=B3?=  =?utf-8?Q?b=C3=A1r?= <test@example.com>`

All the tested clients ignores the double spaces, so it seems there's an issue with the [encoder used](https://github.com/symfony/mime/blob/7.1/Encoder/QpMimeHeaderEncoder.php) for `Symfony\Component\Mime\Address`.

Thanks for your time and input!
