### ISSUE TITLE
HTML content malformed

### ISSUE THREAD

**Issue by jurrid** [zbateson/mail-mime-parser#247]
I’m using your package to parse incoming messages, which we then store in a database. The full message is stored, and any attachments are saved as separate files. However, when viewing the HTML content of some messages, certain parts of the HTML are being malformed during the reading process.

For example:
- The attribute `<meta content="target-densitydpi=device-dpi" name="viewport" />` is being transformed into `<meta content="target-densitydpi?vice-dpi" name="viewport" />` (notice the = has changed to ?).
- Similarly, `<meta content="width=device-width" name="viewport" />` is being transformed into `<meta content="width?vice-width" name="viewport" />`.

#### Steps to Reproduce
Here’s a snippet of code that demonstrates the issue:

```php
$content = file_get_contents('path/to/file/mail.txt');

$message = \ZBateson\MailMimeParser\Message::from($content, true);

var_dump($message->getHtmlContent());
```

I’ve attached a sample email file ([mail.txt](https://github.com/user-attachments/files/18094011/mail.txt)) for testing and debugging purposes. The issue appears to be related to the presence of `=de` in the HTML, but I haven’t been able to identify the exact cause in the code.

**Comment by zbateson** [comment]
Hi @jurrid 

The html part in that mail message has a header that says it's "quoted-printable"-encoded.  The html part associated with it though is not quoted-printable encoded, which uses "=" (followed by two hexadecimal numbers) to encode special characters.

If you remove that header, it'll no longer try to decode "=" characters.

**Comment by jurrid** [comment]
Thanks for the clarification! I believe I’ve identified the part of our system that’s causing the encoding issue. Case closed!
