### ISSUE TITLE
Limit Attachment content stream

### ISSUE THREAD

**Issue by tbyte80** [zbateson/mail-mime-parser#82]
Hello,
first of all thanks for your great work and the very well built parser lib. I'd love to have a small improvement (or advice) fetching attachment data. Consider the following code:

```php
    foreach ($message->getAllAttachmentParts() as $attachment) {

            $cs = $attachment->getContentStream();
            $maxBytes = '2048';
            $cs->getContents($maxBytes);
    }
```
It would be super helpful if I could limit the amount of data, I am pulling out of the stream and to have an indicator whether or not the data exceeds the provided limit.

Background is: I am parsing User Emails that can potentially have large attachments. I need a way to check the size of those files without shoving all the data into main memory.
I know that `StreamInterface` has a `getSize` method. But I don't know how reliable that information is and more importantly is it memory friendly?

Thank you in advance :) !

**Comment by zbateson** [comment]
Hi @tbyte80 

Thanks for the feedback and encouragement :)

I think what you're probably looking for is simply: ``` $cs->read($maxBytes); ```.  MMP uses psr7 streams, you can check out the StreamInterface api here: https://www.php-fig.org/psr/psr-7/#34-psrhttpmessagestreaminterface

About ``` getSize ``` just in case you wonder, it does read to the end of the stream to determine the stream's size in most streams returned if reading from an encoded stream (e.g. base64 or quoted printable) -- the stream needs to be 'read' first.  This is mostly an inefficient implementation, but not a memory-intensive one (bytes are read and discarded, then the stream is rewound).  In your case, you'd probably want to use ``` eof ``` and ``` read ``` instead, more like this:

``` 
/// ... your existing code up to $cs->getContents
while (!$cs->eof()) {
    $s = $cs->read(2048);
    // do stuff with it
}
// ...
```

Hope that helps

**Comment by tbyte80** [comment]
Great answer, thanks! Thanks also for elaborating on `getSize`. It does completely make sense to determine the size that way (discarding what's just read). With the CPU inefficiency I can live for now so that's the quick solution I go for :) .
