### ISSUE TITLE
How to get number of attachments?

### ISSUE THREAD

**Issue by fridzema** [zbateson/mail-mime-parser#86]
Hello, 

I want to process all the attachments in one email. 
But in the function `$message->getAttachmentPart(0);` i need to provide the part. 

How can i know how many parts there are?

**Comment by zbateson** [comment]
Hi @fridzema 

You can call [Message::getAttachmentCount](https://mail-mime-parser.org/api/1.1/classes/ZBateson.MailMimeParser.Message.html#method_getAttachmentCount).

Good luck!
