### ISSUE TITLE
Use in Wordpress Plugin

### ISSUE THREAD

**Issue by Tanzy** [zbateson/mail-mime-parser#89]
Whats the best way to use this library in a Wordpress plugin? As you can't really use composer to get the packages that I'm aware of. (Not PHP is not my main programming language, just playing with it).

Want to use it in a Wordpress Plugin as it saves me having to write a lot more code than I need to is I was using something like Laravel.

**Comment by zbateson** [comment]
Hi @Tanzy 

I haven't worked much with Wordpress specifically, so I can't say what the best way is.  My guess is if it's not using composer already it should just be a matter of loading the classloader and shouldn't matter that it's Wordpress or anything else.
