### ISSUE TITLE
Unable to Get/Access the Content of the Message of mail-mime

### ISSUE THREAD

**Issue by jmarvinr18** [zbateson/mail-mime-parser#91]
Hi Zaahid,

I've been fascinated to the way you conceptualize this package, thus, i choose to use this package for me to have my email messaging project to work. I'm just having some challenge on how i would be able to fetch ONLY the base64 encoded content of the mail-mime I'm receiving. 
![image](https://user-images.githubusercontent.com/40680441/58975490-ad8ece80-87f7-11e9-8395-922916b7da89.png)

I tried to fetch the other headers like the Addresses, Sender, Recipient and Date except for that content. I have tried almost all of your method for getting the parsed message parts but none worked. Here is some of the code i tried. 

`<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use ZBateson\MailMimeParser\MailMimeParser;
use ZBateson\MailMimeParser\Message;
use BeyondCode\Mailbox\InboundEmail;
use ZBateson\MailMimeParser\Header\AbstractHeader;
use ZBateson\MailMimeParser\Message\Part\MessagePart;

class EmailParserController extends Controller
{
 
	public function email_parse(){

	 $parser = new MailMimeParser();

	 $email = InboundEmail::where('id', 27)->first();
	 $message = $parser->parse($email->message);

	 $htmlStream = Message::from($email->message);

	 $getheader = $message->getHeader('content-transfer-encoding');
	 $getcontent = $message->getContent();

	 dd($getheader);

	}

}`
But it is just giving me Null value.

![image](https://user-images.githubusercontent.com/40680441/58975767-563d2e00-87f8-11e9-94a3-3f3ae400e4c7.png)

I hope I can hear from you soon to have some help. Thank you so much.

**Comment by zbateson** [comment]
Hi @jmarvinr18 

From the looks of it, you're trying to retrieve the contents of an attachment.  You should be able to do something like:

`echo $message->getAttachmentPart(0)->getContent();`

There's a usage guide in the documentation explaining how to access various parts of a message with links to the public API.

Good luck!
Zaahid

**Comment by jmarvinr18** [comment]
> Hi @jmarvinr18
> 
> From the looks of it, you're trying to retrieve the contents of an attachment. You should be able to do something like:
> 
> `echo $message->getAttachmentPart(0)->getContent();`
> 
> There's a usage guide in the documentation explaining how to access various parts of a message with links to the public API.
> 
> Good luck!
> Zaahid

Thank you for your response Zaahid! I actually figured out that i was accessing an attachment. Do you have i have how to make it as an email body rather than as attachment?

**Comment by zbateson** [comment]
The library only considers "text/plain" or "text/html" as "body" parts.  It's not an issue of the email, just how the library interprets it.
