### ISSUE TITLE
Enforcement of base64 in attachments

### ISSUE THREAD

**Issue by martinhartmann** [zbateson/mail-mime-parser#98]
Why is base64 encoding enforced in attachments no matter the content type?

https://github.com/zbateson/mail-mime-parser/blob/05e7579f3f37a4fd67933f1d059fefd78db88835/src/Message/Helper/MultipartHelper.php#L351-L353

I added a `text/plain` attachment but it will only be available as base64 encoded data.

**Comment by zbateson** [comment]
That's a good question... my off-the-top of my head reasons are:

* Not wanting to decide what mime types are in fact "text" (e.g. text/plain vs. text/rtf, or application/javascript)
* Not wanting to write code that tries to determine if no encoding is needed, or if quoted printable makes sense vs. base64
* Besides slightly larger emails, not seeing much benefit in spending time making those determinations

Having said that, it's not that I'm against doing it.  What if we added an additional parameter to the method to allow the default 'base64' to be overridden, so at least it's a user-decision?

**Comment by martinhartmann** [comment]
> What if we added an additional parameter to the method to allow the default 'base64' to be overridden, so at least it's a user-decision?

At least I would be very happy about it. ;)

**Comment by zbateson** [comment]
Released in 1.2.0.

**Comment by martinhartmann** [comment]
Thanks, working flawlessly!
